[project]
name = "stealthmole-mcp"
version = "0.1.0"
description = "MCP server for StealthMole threat intelligence and dark web monitoring APIs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.0.1",
    "pyjwt>=2.8.0",
    "httpx>=0.27.0",
]
